# Generated by Django 2.0.8 on 2019-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_for_slider/', verbose_name='Изображение')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Основной текст')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать объявление?')),
            ],
            options={
                'verbose_name': 'Изображение(слайдер)',
                'verbose_name_plural': 'Изображения(слайдер)',
            },
        ),
    ]
