# Generated by Django 2.0.8 on 2019-02-03 08:54

import autoslug.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('handicrafts', '0002_auto_20190202_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Название каталога')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False,
                                                       populate_from='label', unique=True)),
                ('image', models.ImageField(upload_to='images_for_catalogs/', verbose_name='Картинка для каталога')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать каталог?')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='children', to='handicrafts.Catalog',
                                            verbose_name='Родительский каталог')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
    ]
