# Generated by Django 2.0.8 on 2019-02-03 13:33

import autoslug.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('handicrafts', '0003_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75, unique=True, verbose_name='Название товара')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False,
                                                       populate_from='label', unique=True)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать товар?')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                              to='handicrafts.Catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_for_products/', verbose_name='Изображение')),
                ('priority', models.IntegerField(default=5, verbose_name='Приоритет показа')),
                ('created_date',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления картинки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                              to='handicrafts.Product')),
            ],
            options={
                'verbose_name': 'Изображение к товару',
                'verbose_name_plural': 'Изображения к товару',
                'ordering': ['priority'],
            },
        ),
    ]
